---
- name: reloaded httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: (ansible_facts['distribution'] == "CentOS")
- name: reloaded apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: (ansible_facts['distribution'] == "Ubuntu")

