---
- name: Archivo configuracion httpd reverse
  template:
    src: proxy-cluster.j2
    dest: /etc/httpd/conf.d/proxy-cluster.conf
  notify: reloaded httpd
# tasks file for httpd
- firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes
- firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
    immediate: yes
